CREATE OR REPLACE TASK A
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
AS
  SELECT 1 AS task_a;

CREATE OR REPLACE TASK B
  WAREHOUSE = COMPUTE_WH
  AFTER A
AS
  SELECT vinohd();

CREATE OR REPLACE TASK C
  WAREHOUSE = COMPUTE_WH
  AFTER B
AS
  SELECT 3 AS task_c;

CREATE OR REPLACE TASK D
  WAREHOUSE = COMPUTE_WH
  AFTER B
AS
  SELECT kumar();

CREATE OR REPLACE TASK E
  WAREHOUSE = COMPUTE_WH
  AFTER C, D
AS
  SELECT 5 AS task_e;


 CREATE OR REPLACE TASK X
  WAREHOUSE = COMPUTE_WH
  AFTER C, A
AS
  SELECT 1 AS task_x; 

  

ALTER TASK X RESUME;
ALTER TASK E RESUME;
ALTER TASK D RESUME;
ALTER TASK C RESUME;
ALTER TASK B RESUME;
ALTER TASK A RESUME;

ALTER TASK A SUSPEND;
ALTER TASK B SUSPEND;
ALTER TASK C SUSPEND;
ALTER TASK D SUSPEND;
ALTER TASK E SUSPEND;
ALTER TASK X SUSPEND;



CREATE OR REPLACE DYNAMIC TABLE DT_A
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 MINUTE'
AS
  SELECT SEQ4() AS tmp FROM MY_VALUES;
  
CREATE OR REPLACE DYNAMIC TABLE DT_B
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 MINUTE'
  REFRESH_MODE = INCREMENTAL
  INITIALIZE = ON_CREATE
  DEPENDS_ON = (DT_A)
AS
  SELECT SEQ4() AS tmp FROM DUMMY.TMP.MY_VALUES;

CREATE OR REPLACE DYNAMIC TABLE DT_C
  WAREHOUSE = COMPUTE_WH
  REFERENCE_TABLES = (DT_B)
AS
  SELECT SEQ4() AS tmp FROM MY_VALUES;

CREATE OR REPLACE DYNAMIC TABLE DT_D
  WAREHOUSE = COMPUTE_WH
  REFERENCE_TABLES = (DT_B)
AS
  SELECT SEQ4() AS tmp FROM MY_VALUES;

CREATE OR REPLACE DYNAMIC TABLE DT_E
  WAREHOUSE = COMPUTE_WH
  REFERENCE_TABLES = (DT_C, DT_D)
AS
  SELECT SEQ4() AS tmp FROM MY_VALUES;

CREATE OR REPLACE DYNAMIC TABLE DT_X
  WAREHOUSE = COMPUTE_WH
  REFERENCE_TABLES = (DT_C, DT_A)
AS
  SELECT SEQ4() AS tmp FROM MY_VALUES;