-- DATA SHARING

USE ROLE ACCOUNTADMIN;

-- Create a database and schema
CREATE DATABASE SHARING_DB;
CREATE SCHEMA SHARING_DB.PUBLIC;

-- Create a sample table with some data
CREATE OR REPLACE TABLE SHARING_DB.PUBLIC.SALES_DATA (
  PRODUCT_ID INT,
  SALES_DATE DATE,
  SALES_AMOUNT DECIMAL(10, 2),
  CUSTOMER_INFO VARIANT
);
-- Insert some sample data, including semi-structured data
INSERT INTO SHARING_DB.PUBLIC.SALES_DATA (PRODUCT_ID, SALES_DATE, SALES_AMOUNT, CUSTOMER_INFO)
SELECT 
  column1, column2, column3, PARSE_JSON(column4)
FROM (VALUES
  (101, '2025-09-08'::DATE, 50.00, '{"name":"John Doe", "email":"john.doe@example.com"}'),
  (102, '2025-09-08'::DATE, 75.50, '{"name":"Jane Smith", "email":"jane.smith@example.com"}')
);
-- Let's share a secure view to mask sensitive data
CREATE OR REPLACE SECURE VIEW SHARING_DB.PUBLIC.SALES_VIEW AS
SELECT 
  PRODUCT_ID,
  SALES_DATE,
  SALES_AMOUNT,
  CUSTOMER_INFO:name::STRING AS CUSTOMER_NAME
FROM SHARING_DB.PUBLIC.SALES_DATA;

CREATE SHARE SALES_DATA_SHARE;

-- Grant USAGE on the database and schema
GRANT USAGE ON DATABASE SHARING_DB TO SHARE SALES_DATA_SHARE;
GRANT USAGE ON SCHEMA SHARING_DB.PUBLIC TO SHARE SALES_DATA_SHARE;

-- Grant SELECT on the secure view
GRANT SELECT ON VIEW SHARING_DB.PUBLIC.SALES_VIEW TO SHARE SALES_DATA_SHARE;

-- Replace 'CONSUMER_ACCOUNT_LOCATOR' with the actual account locator
ALTER SHARE SALES_DATA_SHARE ADD ACCOUNTS = IAC62214;

-- Replace 'CONSUMER_ACCOUNT_LOCATOR' with the actual account locator
ALTER SHARE SALES_DATA_SHARE ADD ACCOUNTS = VQ95322;



-- REPLICATION

USE ROLE ORGADMIN;

-- Replace with your actual org and account IDs
SELECT SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER('RGRDYNG.WWC63822', 'ENABLE_ACCOUNT_DATABASE_REPLICATION', 'true');
SELECT SYSTEM$GLOBAL_ACCOUNT_SET_PARAMETER('RGRDYNG.CROSS_REGION_UE2', 'ENABLE_ACCOUNT_DATABASE_REPLICATION', 'true');

USE ROLE ACCOUNTADMIN;

CREATE DATABASE REPLICATION_DEMO;
CREATE SCHEMA REPLICATION_DEMO.SALES;
CREATE TABLE REPLICATION_DEMO.SALES.SALES_TRANSACTIONS (
  TXN_ID INT,
  TXN_DATE DATE
);
INSERT INTO REPLICATION_DEMO.SALES.SALES_TRANSACTIONS VALUES (1, '2025-09-10');

-- Replace with your actual org and target account IDs
CREATE REPLICATION GROUP RG_SALES
  OBJECT_TYPES = DATABASES
  ALLOWED_DATABASES = REPLICATION_DEMO
  ALLOWED_ACCOUNTS = RGRDYNG.CROSS_REGION_UE2;
 