-- ENABLE AI 
use role accountadmin;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';
SHOW PARAMETERS LIKE 'CORTEX_ENABLED_CROSS_REGION' IN ACCOUNT;

CREATE OR REPLACE DATABASE PROVIDER_DB;

CREATE OR REPLACE SCHEMA READER_SCHEMA WITH MANAGED ACCESS;
CREATE OR REPLACE SCHEMA SAME_CLOUD_SAME_REGION WITH MANAGED ACCESS;
CREATE OR REPLACE SCHEMA SAME_CLOUD_CROSS_REGION WITH MANAGED ACCESS;
CREATE OR REPLACE SCHEMA CROSS_CLOUD WITH MANAGED ACCESS;

CREATE OR REPLACE SEQUENCE PROVIDER_DB.READER_SCHEMA.SEQ_ODD
    START = 1
    INCREMENT = 2
    COMMENT = 'Generates odd numbers starting from 1'
    ORDER;

CREATE OR REPLACE SEQUENCE PROVIDER_DB.READER_SCHEMA.SEQ_EVEN
    START = 2
    INCREMENT = 2
    COMMENT = 'Generates even numbers starting from 2'
    ORDER;

CREATE OR REPLACE TABLE PROVIDER_DB.READER_SCHEMA.STANDARD_TABLE (
    ID NUMBER(38,0) DEFAULT SEQ_ODD.NEXTVAL,
    TEXT_FIELD VARCHAR(100)
) 
COMMENT = 'Standard table with odd sequence numbers'
DATA_RETENTION_TIME_IN_DAYS = 1;

CREATE OR REPLACE TRANSIENT TABLE PROVIDER_DB.READER_SCHEMA.TRANSIENT_TABLE (
    ID NUMBER(38,0) DEFAULT SEQ_EVEN.NEXTVAL,
    TEXT_FIELD VARCHAR(100)
) 
COMMENT = 'Transient table with even sequence numbers'
DATA_RETENTION_TIME_IN_DAYS = 0; 



INSERT INTO STANDARD_TABLE(TEXT_FIELD) VALUES('a'), ('b'), ('c'), ('d'),('e');
INSERT INTO TRANSIENT_TABLE(TEXT_FIELD) VALUES('a'), ('b'), ('c'), ('d'),('e');

CREATE OR REPLACE VIEW PROVIDER_DB.READER_SCHEMA.STANDARD_VIEW AS 
SELECT * FROM PROVIDER_DB.READER_SCHEMA.STANDARD_TABLE 
UNION ALL 
SELECT * FROM PROVIDER_DB.READER_SCHEMA.TRANSIENT_TABLE;

CREATE OR REPLACE SECURE VIEW PROVIDER_DB.READER_SCHEMA.SECURE_VIEW AS 
SELECT * FROM PROVIDER_DB.READER_SCHEMA.STANDARD_TABLE 
UNION ALL 
SELECT * FROM PROVIDER_DB.READER_SCHEMA.TRANSIENT_TABLE;

CREATE OR REPLACE MATERIALIZED VIEW PROVIDER_DB.READER_SCHEMA.MATERIALIZED_VIEW AS 
SELECT * FROM PROVIDER_DB.READER_SCHEMA.STANDARD_TABLE;

CREATE OR REPLACE SECURE MATERIALIZED VIEW PROVIDER_DB.READER_SCHEMA.SECURE_MATERIALIZED_VIEW AS 
SELECT * FROM PROVIDER_DB.READER_SCHEMA.TRANSIENT_TABLE;

CREATE OR REPLACE FUNCTION PROVIDER_DB.READER_SCHEMA.SQUARE_NUMBER(NUM FLOAT)
RETURNS FLOAT
LANGUAGE SQL
AS
$$
    NUM * NUM
$$;

CREATE OR REPLACE SECURE FUNCTION PROVIDER_DB.READER_SCHEMA.CUBE_NUMBER(NUM FLOAT)
RETURNS FLOAT
LANGUAGE SQL
AS
$$
    NUM * NUM * NUM
$$;

CREATE OR REPLACE TEMPORARY STAGE PROVIDER_DB.READER_SCHEMA.MY_TEMP_STAGE
  FILE_FORMAT = (TYPE = 'CSV' 
                FIELD_DELIMITER = ',' 
                SKIP_HEADER = 1 
                FIELD_OPTIONALLY_ENCLOSED_BY = '"'
                NULL_IF = ('NULL', 'null')
                EMPTY_FIELD_AS_NULL = TRUE
                COMPRESSION = AUTO)
  COPY_OPTIONS = (ON_ERROR = 'CONTINUE'
                 FORCE = TRUE
                 SIZE_LIMIT = 100000000)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Temporary stage for CSV files';

CREATE OR REPLACE FILE FORMAT PROVIDER_DB.READER_SCHEMA.MY_CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  COMPRESSION = AUTO;

CREATE OR REPLACE HYBRID TABLE PROVIDER_DB.READER_SCHEMA.CUSTOMER_HYBRID (
    customer_id NUMBER,
    name VARCHAR,
    email VARCHAR,
    signup_date DATE
);
